title:            'MATHVEC'

window_height:       0.8
window_width:        0.4
right_panel_width:  200

textbox_width:      50
textbox_height:     10        

canvas_width:       500
canvas_height:      150
canvas_textsize_min: 6
canvas_textsize_max: 18

figure_height:      1
figure_width:       3
figure_dpi:         300      
figure_textsize:    20

theme:              light_mode