title:            'MATHVEC'

window_height:      700
window_width:       1000
window_y_offset:    20
right_panel_width:  200

textbox_width:      50
textbox_height:     10        

canvas_width:       500
canvas_height:      150
canvas_textsize:    12

figure_height:      1
figure_width:       3
figure_dpi:         300      
figure_textsize:    20

theme:              dark_mode